<?php
/** @var $this \G4NReact\MsCatalogMagento2\Block\Adminhtml\Catalog\AbstractEditTabDocumentStorefront */

foreach ($this->getDocument() as $documents) :
    $documentList = $documents->getData(); ?>
    <?php if ($documentList && count($documentList)): ?>
    <table class="data-grid">
        <thead>
        <tr>
            <th class="data-grid-th"><?= __('Name') ?></th>
            <th class="data-grid-th"><?= __('Value') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($documentList as $document) :
            $value = is_array($document->getValue()) ? implode(', ', $document->getValue()) : $document->getValue();
            ?>
            <tr class="data-row" style="border-bottom: 1px solid #d6d6d6">
                <td class="data-grid-checkbox-cell">
                    <span style="color: black; display: block; padding: 1em;"><?= $document->getName(); ?></span>
                </td>
                <td class="data-grid-checkbox-cell">
                    <span style="color: green; display: block; padding: 1em;"><?= htmlentities($value); ?></span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
<?php endforeach; ?>

<script>
    require([
        'jquery',
        'prototype',
    ], function (jQuery) {
        function reindex() {
            params = {
                id: '<?= $this->getId()?>',
                object_type: '<?= $this->getObjectType()?>',
                store_id: '<?= $this->getStoreId()?>',
                isAjax: true
            };

            new Ajax.Request('<?php /* @escapeNotVerified */ echo $this->getAjaxUrl() ?>', {
                loaderArea: false,
                asynchronous: true,
                parameters: params,
                onSuccess: function (transport) {
                    // temporary
                    if (window && window.location && typeof window.location.reload === 'function') window.location.reload(true);
                }
            });
        }

        jQuery('#reindex_react_storefront_data').click(function () {
            reindex();
        });
    });
</script>

<?php echo $this->getButtonHtml() ?>
