<?php
/** @var $this \G4NReact\MsCatalogMagento2\Block\Adminhtml\Catalog\AbstractEditTabDocument*/

foreach ($this->getDocument() as $documents) :
$documentList = $documents->getData(); ?>
    <?php if($documentList && count($documentList)): ?>
    <table class="data-grid">
        <thead>
        <tr>
            <th class="data-grid-th"><?= __('Name') ?></th>
            <th class="data-grid-th"><?= __('Value') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($documentList as $document) :
            $value = is_array($document->getValue()) ? implode(', ', $document->getValue()) : $document->getValue();
            ?>
            <tr class="data-row" style="border-bottom: 1px solid #d6d6d6">
                <td class="data-grid-checkbox-cell">
                    <span style="color: black; display: block; padding: 1em;"><?= $document->getName(); ?></span>
                </td>
                <td class="data-grid-checkbox-cell">
                    <span style="color: green; display: block; padding: 1em;"><?= $value; ?></span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
<?php endforeach; ?>
